### ISSUE TITLE
Wiki is broken

### ISSUE THREAD

**Issue by Jentsch** [fredlund/McErlang#3]
Hi,

it looks like the project wiki isn't working any more.

https://babel.ls.fi.upm.es/trac/McErlang/ shows:
```
Error

TracError: The Trac Environment needs to be upgraded.

Run "trac-admin /srv/trac/McErlang upgrade"
```

I hope this is the right place for this issue.

Kind regards
Jentsch

**Comment by fredlund** [comment]
Thanks for the report! We upgraded the machine with the trac and this failure ocurred.
